spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_dev
    username: dev_user
    password: user
    platform: mysql
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: true
    hibernate:
          ddl-auto: validate
